# Generated by Django 4.2.2 on 2023-05-10 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_alter_category_id_alter_demodefaultmodel_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
                ("area", models.FloatField()),
                ("english_name", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="city_images/")),
                (
                    "super_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
                ("area", models.FloatField()),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.city"
                    ),
                ),
                (
                    "super_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.city"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.region"
                    ),
                ),
                (
                    "super_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirQualityIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm25", models.FloatField()),
                ("pm10", models.FloatField()),
                ("ozone", models.FloatField()),
                ("carbon_monoxide", models.FloatField()),
                ("sulfur_dioxide", models.FloatField()),
                ("nitrogen_dioxide", models.FloatField()),
                ("real_time_index", models.IntegerField()),
                ("quality_evaluation", models.CharField(max_length=50)),
                ("primary_pollutant", models.CharField(max_length=50)),
                ("aqi", models.IntegerField()),
                ("update_time", models.DateTimeField()),
                (
                    "city_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.city"
                    ),
                ),
                (
                    "station_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.station"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirQualityConcentration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm25", models.FloatField()),
                ("pm10", models.FloatField()),
                ("ozone", models.FloatField()),
                ("carbon_monoxide", models.FloatField()),
                ("sulfur_dioxide", models.FloatField()),
                ("nitrogen_dioxide", models.FloatField()),
                ("update_time", models.DateTimeField()),
                (
                    "station_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.station"
                    ),
                ),
            ],
        ),
    ]
