# Generated by Django 4.2.2 on 2023-06-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_city_region_station_airqualityindex_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemoDefaultModel",
        ),
        migrations.RemoveField(
            model_name="demomodel",
            name="foreign_key_field",
        ),
        migrations.DeleteModel(
            name="DemoModelRequire",
        ),
        migrations.RemoveField(
            model_name="richtextdemo",
            name="category",
        ),
        migrations.RemoveField(
            model_name="richtextdemo",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="richtextdemo",
            name="user",
        ),
        migrations.AlterField(
            model_name="region",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="DemoForeignKey",
        ),
        migrations.DeleteModel(
            name="DemoModel",
        ),
        migrations.DeleteModel(
            name="RichTextDemo",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
