# Generated by Django 4.2.2 on 2023-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_delete_demodefaultmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airqualityindex",
            name="aqi",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
