# Generated by Django 4.2.2 on 2023-06-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0005_alter_airqualityindex_aqi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Water",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_no", models.CharField(max_length=100)),
                ("water_amount", models.FloatField()),
                ("update_time", models.DateTimeField(auto_now_add=True)),
                ("create_time", models.DateTimeField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.city"
                    ),
                ),
                (
                    "super_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
